ide:
	open kgn.rkt dev.rkt dialog-utils.rkt main.rkt sparql-utils.rkt

emacs:
	Emacs kgn.rkt dev.rkt dialog-utils.rkt main.rkt sparql-utils.rkt
#	ae kgn.rkt dev.rkt dialog-utils.rkt main.rkt sparql-utils.rkt names.rkt utils.rkt

clean:
	rm -r -f *.rkt#* */*.rkt#* */*/*.rkt#* compiled */compiled */*/compiled

linux:
	drracket ui.rkt main.rkt sparql-utils.rkt dialog-utils.rkt &

